export default function Illio() {
  return (
    <svg
      width="18"
      height="11"
      viewBox="0 0 18 11"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="1"
        y="1"
        width="16"
        height="9"
        rx="1.5"
        stroke="#D87906"
        strokeOpacity="0.5"
        strokeWidth="0.5"
      />
      <rect
        x="2"
        y="2"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="2"
        y="4"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="4"
        y="4"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="7"
        y="8"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="2"
        y="8"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="13"
        y="4"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="9"
        y="8"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="15"
        y="4"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="11"
        y="8"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="15"
        y="8"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="2"
        y="6"
        width="10"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="4"
        y="2"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="13"
        y="6"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="6"
        y="2"
        width="10"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
      <rect
        x="15"
        y="6"
        width="1"
        height="1"
        rx="0.5"
        fill="#D87906"
        fillOpacity="0.5"
      />
    </svg>
  );
}
